language: python

sudo: false

python:
  - "2.7"
  - "3.6"
  - "3.7-dev"

env:
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=master

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO=2.0
    - python: "2.7"
      env: DJANGO=2.1
    - python: "2.7"
      env: DJANGO=master
    - python: "3.6"
      env: DJANGO=1.9
    - python: "3.7-dev"
      env: DJANGO=1.9
    - python: "3.6"
      env: DJANGO=1.10
    - python: "3.7-dev"
      env: DJANGO=1.10
    - python: "3.6"
      env: DJANGO=1.11
    - python: "3.7-dev"
      env: DJANGO=1.11
  include:
    - python: "3.7-dev"
      env: TOXENV=flake8
  allow_failures:
    - env: DJANGO=master

install:
  - pip install tox-travis coveralls

script:
  - tox

after_success:
  - coveralls
