language: python

sudo: false

env:
  - TOX_ENV=py27-flake8
  - TOX_ENV=py34-flake8
  - TOX_ENV=py27-dj15
  - TOX_ENV=py27-dj16
  - TOX_ENV=py27-dj17
  - TOX_ENV=py27-dj18
  - TOX_ENV=py27-dj19
  - TOX_ENV=py27-dj20
  - TOX_ENV=py27-djmaster
  - TOX_ENV=py34-dj15
  - TOX_ENV=py34-dj16
  - TOX_ENV=py34-dj17
  - TOX_ENV=py34-dj18
  - TOX_ENV=py34-dj19
  - TOX_ENV=py34-dj20
  - TOX_ENV=py34-djmaster

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py27-djmaster
    - env: TOX_ENV=py34-djmaster

install:
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
